feat: 添加 Switch ValueType 展示类型
TurboostTeam/antd-simple-table pull request #18
Opened 2020-05-28 03:57 UTC by Peatechen

2020-05-28 04:01 UTC, linxianxi commented on src/interfaces/ValueObjectType.ts
> +  disable?: boolean;
disabled

2020-05-28 07:22 UTC, linxianxi approved these changes

2020-06-01 05:56 UTC, xudongcc requested changes

2020-06-01 05:56 UTC, xudongdev commented on src/interfaces/ValueObjectType.ts
> -    value: string | number | React.ReactText[],
为什么改成 Any ？

2020-06-01 05:56 UTC, xudongdev commented on src/interfaces/ValueObjectType.ts
>  export interface BaseValueObjectType {
好像 ESLint 没有格式化换行？

2020-06-01 06:00 UTC, Peatechen commented on src/interfaces/ValueObjectType.ts
> -    value: string | number | React.ReactText[],
antd 是用 any

2020-06-01 06:14 UTC, Peatechen commented on src/interfaces/ValueObjectType.ts
>  export interface BaseValueObjectType {
提交的时候 lint-staged 有感叹号提示。再试一次

2020-06-01 06:27 UTC, xudongcc approved these changes

2020-06-01 06:28 UTC, merged